using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ExtendsStudent;

namespace MyTestClass
{
    [TestClass]
    public class StudentExtensionTest
    {
        StudentExtension testObject;
        [TestMethod]
        public void StudyTest()
        {
            DTO.Student student = default(DTO.Student);
            testObject.Study(student);
            Assert.Fail("autogenerated");
        }
    }
}